### ISSUE TITLE
Version 0.7.3 throws an error "Callback must be a function" on delete.

### ISSUE THREAD

**Issue by KonradNojman** [voidcosmos/npkill#87] opened 2021-01-03 20:37 UTC
**Describe the bug**
After searching in the directory and finding `node_modules` folders, the `npkill` throws an error 

> Callback must be a function

when pressing space on any of the folders.
Tried the version `0.7.0` and problem doesn't occur. 

**To Reproduce**
1. Go to the folder with multiple projects
2. Use `npx npkill` or `npm i -g npkill` and `npkill`
3. Wait for the search to be completed
4. Press space bar on one of the results
5. The error message occurs "Callback must be a function"

**Expected behavior**
The node_modules folder should be deleted.

 - OS: Windows (tested on the `bash` and `cmd` console)
 - Version 0.7.3 (on 0.7.0 it works, didn't test versions in between)

**Comment by zaldih** [comment] 2021-01-03 20:59
Hi! 
Thank you very much to open this issue and detail it.

It's definitely a bug introduced apparently in version 0.7.3 and that comes dragged from #81 (to try to fix a critical bug).
It has been caused by a refactoring of the delete method in windows (#86) and we hope to have time to fix it soon.

Just out of curiosity, what version of node do you have?

**Comment by sisPedro** [comment] 2021-01-04 23:46
Hey @zaldih, same problem here. node version in my case is v10.13.0

**Comment by KonradNojman** [comment] 2021-01-07 18:37
Hey!
Thanks for the response @zaldih 👍 
I have Node version 10.15.3

**Comment by ognjenjevremovic** [comment] 2021-02-21 19:35
Hey @zaldih, I just found out about `npkill` after searching on how to recursively remove all of the (space heavy) `node_modules` directories from some of the projects I have contributed to recently (as it was taking a good portion of my SSD).
I wanted to give props for this tool and also wanted to contribute back to the project.

Is this issue resolved or it is still open and up for grabs (if no one is actually working on it)?

I see the issue is labeled and also seems of a bit higher priority (compared to others).
Will this be a good issue for newcomers to the project?

May you give slight hints on where the problem might be located and is it affecting all Node versions / platforms or only a small subset (if so, how can it be easily reproducible)?

Many thanks!

**Comment by zaldih** [comment] 2021-02-24 20:28
Hey @ognjenjevremovic !
First of all, thank you very much for your interest! It's appreciated :)

Currently it looks like no one has gotten around to it, so if you want it, it's all yours. I'm going to tell you all the information I have (so anyone else can discuss options as well).

The problem resides only in this method https://github.com/voidcosmos/npkill/blob/9067388656502c2d281ae9bec780ed56584cc1bd/src/services/windows-files.service.ts#L40 , so to fix this problem it will not be necessary to touch any other file.

The method stopped working just in this change 81ad353e5b2430cb62a126aa8e329375e539305e .

**Why change it if it was working?** Because it seems that this method had problems with symbolic links, described in the issue mentioned a few messages ago.

**Why does it fail now?** I am almost certain that the new method is relatively new and does not work with some versions of node.


The fastest and most efficient solution would be to use some library like '**RIMRAF**' , but we have tried to avoid using as many libraries as possible to make npkill as 'independent' as possible, so it will remain as a last option. But at this point, if nobody can't think of a different solution, it will be better to use it and implement it :D.


And to know if the problem is solved, you should try in windows to delete several node_modules with different versions of node (for example, v10, v12, v14 and v15). And make sure that the problem described in #81 does not occur again, following the steps described there.


Again, thanks for the interest, to you and everyone else for participating in any way in the project :heart:

**Comment by ognjenjevremovic** [comment] 2021-02-25 22:00
Thank you for your detailed overview of the issue @zaldih 🙂 .

I would like to give this one a closer look.
Is this issue present only on `Windows` machines or other platforms are affected too? Currently, I do not have access to `Windows` platform myself, but perhaps I can spin an azure pipeline in order to have it tested (if and when i have the fix ready).

I completely understand your concern of using 3rd party modules; I'll see if I can provide a fix with native node modules without relying on `rimraf` (or similar npm / 3rd party packages).
Do you know if this issue is present only on certain versions of `Node` on `Windows` or all versions are affected?
Also, what is the least supported `Node` version of `npkill` package?

Feel free to assign this issue to me 🙂 .
I hope I'll get some time during the upcoming weekend to dedicate to this issue. I'll post and update when I have some.

Best

**Comment by KonradNojman** [comment] 2021-02-25 22:32
Hi @ognjenjevremovic! Nice to see you are interested in this bug 🚀 
If you don't find any way of testing your changes on `Windows` you can ping me. If I have some time, maybe I will be able to checkout your branch and test it out locally. 
Not promising anything, because I'm a little swamped with work right now, but I'll try to help you out if needed 🙌  🙂

**Comment by ognjenjevremovic** [comment] 2021-02-26 09:07
Cheers @KonradNojman. That sounds wonderful (and it would be a great time saver)! 🚀 🙂 
I'll try post an update sometime during next week, when I hope I'll have more info regarding this.

**Comment by suman-saket** [comment] 2021-02-26 12:48
In my windows system, when i try to delete node_modules,it  is throwing an error of Callback must be a function. 
npkill version-o.7.3

**Comment by ognjenjevremovic** [comment] 2021-02-27 17:14
@KonradNojman @suman-saket I just made a PR that addresses this issue https://github.com/voidcosmos/npkill/pull/88.
If you are running `Windows` platform and would like to check the changes before (and if) they make it to a release, you may test the non-release branch locally, by:
 * cloning the repository,
 * checking out `4fbbb83` revision,
 * running `npm i && npm run build` from the cloned repository,
 * installing it from the local file system.

If you would like to test it on a *dummy* project (which I would strongly advise you to, before the code makes it to a production release),  you can setup the environment (if you completed the previously outlined steps) by:
 * creating a new directory and initializing it as an `npm` project by running `mkdir test-npkill && cd test-npkill && npm run init -y`,
 * making a few subdirectories and repeating the process of initializing a new npm project inside them `mkdir a && cd a && npm init -y` as well as installing some dependencies to a project (any would work - this is just so you have a `node_modules` inside of those subdirectories),
 * repeating the previous process a few times but making directories `b`, `c`, `d` as siblings to directory `a`,
 * going back to the root project `test-npkill` and installing the non-release version (local version you previously build) with included changes from the `4fbbb83` HEAD by running `npm i /absolute/path/to/the/cloned/npm/git/project/directory`.

Of course these steps are more of a guideline rather than the *steps to test / reproduce*.
As long as you use the `4fbbb83` HEAD with the included changes and running the local version of `npkill` tool from a directory that has `node_modules` as children you'll be able to run the CLI without issues 🙂 .

**Comment by KonradNojman** [comment] 2021-02-28 19:45
Thanks @ognjenjevremovic for the instructions. I'll try to do some tests next week and let you know what are the results or if I have any questions 👍
Do you think it's necessary to test those changes on multiple versions of node? Or only one should be fine? Any specific version/versions you would like it to get tested on? 🙂
Cheers!

**Comment by ognjenjevremovic** [comment] 2021-03-01 15:47
I think the one should be fine, although the more the merrier 🙂 .
However, only versions below `12.10.0` are affected with this change (on `Windows` platform).

I tested it on `LTS`, `v15.3.0` and `v10.15.3`. However, on a `POSIX` operating system (with a few tweaks in the code in order to reproduce the issue, as I do not have access to a `win32` platform atm).

I think versions below `v10` can be ignored, as the support for version 10 and below is about to expire later this year (in April). But it wouldn't hurt if you have ways of testing it on more than one version of `Node`.

Feel free to ping me if you need any assistance testing this 🙂 .

**Comment by KonradNojman** [comment] 2021-03-07 16:44
Hi @ognjenjevremovic @zaldih !
Sorry for the delay 😅 
Finally I had a chance to check out the changes for this issue. Works awesome ✅ 🚀 

I've reviewed the PR and accepted it after testing on Windows. Please, @zaldih also check the code as I'm not that familiar with the codebase and I could miss something important. 💪 

--- 
When testing I think I maybe found one or 2 new bugs, so I'll check if they already have issues created for them, and if not I'll try to gather more data on them and post soon ;)

**Comment by ognjenjevremovic** [comment] 2021-03-07 17:53
Thank you for the feedback and for testing the changes locally (prior to release) ❤️ .

Please do feel free to make a write up of the issue(s) you have found when testing the changes.
We surely don't want to replace one bug with another 😄 .

**Comment by KonradNojman** [comment] 2021-03-07 17:54
Ok, after checking those issues I think one of them might be connected with this PR. 
When using the local version of the npkill builded using steps above i have a weird jumping effect in the terminal when deleting (see gif) 

![npkill_bug](https://user-images.githubusercontent.com/60238331/110249308-df593a00-7f75-11eb-80a9-99ee1fa5e49d.gif)

I don't know if this is because of the local build somehow or there could be some change in this PR that might cause this. 
@ognjenjevremovic @zaldih did you ever have this problem and have an idea what might cause it? 

(since production v0.7.3 doesn't work for me) I've checked with `npx npkill@0.7.2` and the problem doesn't occur.

**Comment by zaldih** [comment] 2021-03-08 15:26
Hi guys!

Sorry for the delay. I have access to my machines again. I'm going to check everything :)

Thanks so much @ognjenjevremovic  for all the details and for the PR, and @KonradNojman being able to test it and give so much feedback.
I'm going to check everything and hopefully I'll be able to launch these changes in a while!

**Comment by zaldih** [comment] 2021-03-08 21:47
Hey @KonradNojman ! Good point regarding the flicker bug. I have found the cause: now the delete method in windows is synchronous, so the UI will 'freeze' while performing the delete job. Then, when the process finishes, it updates the status to "deleting..." and a few ms later, it changes to "deleted".

I've added a small commit to fix this and refresh the screen before starting the process.

**Comment by KonradNojman** [comment] 2021-03-09 08:43
Awesome 🚀 
I hope I have some time today after work to quickly test your commit and let you know if that did the trick.

**Comment by ognjenjevremovic** [comment] 2021-03-09 13:03
Hey @KonradNojman, I apologize for I have totally missed your report on the flickering issue.
Thank you for posting the update and reporting the issue! 🙂 
Yeah it seems to me that it have been introduced in this PR (thanks to @zaldih for finding the cause of it).

Thank you @zaldih for going through the PR and for finding the solution to these flickers 🙂 . Great job!
You were really fast on debugging and addressing the issue.

I'll be following the issue updates closely, though I might be reporting back with a short delay since I'll be offline for the next few days (with very limited time available online).
I'm happy to address any other issues that might have been introduced with this PR, if you find more.
Once again, thank you both for your time, thorough investigation and all the help. 🚀

**Comment by zaldih** [comment] 2021-03-09 18:34
@ognjenjevremovic Don't worry! in fact it's a silly mistake **I made** when designing the rendering flow that I already suspected a long time ago that in windows was going strange.

**Closed** 2021-03-11 22:55 UTC
Labels: bug, help wanted
