### ISSUE TITLE
Calculating stats is  loading infinity, don't show the size 

### ISSUE THREAD

**Issue by mehedi-imun** [voidcosmos/npkill#182] opened 2024-05-31 15:18 UTC
![image](https://github.com/voidcosmos/npkill/assets/92694753/78ad519b-4b10-4482-b767-97d61b75841f)

**Comment by zaaakher** [comment] 2024-05-31 17:00
Duplicate of #181 

In the meantime, you can use `npx npkill@0.11.3`

**Comment by zaldih** [comment] 2024-06-01 11:05
Thank you for opening this issue.
As the colleague says, this problem is related to the other issue. Let's follow this there.

**Closed by zaldih** 2024-06-01 11:05 UTC
Labels: duplicate

**Comment by mehedi-imun** [comment] 2024-06-16 12:44
Thank you
