### ISSUE TITLE
[Bug] running in ~/ in macOS takes ~/ itself as option and shows the entire disk usage of the folder

### ISSUE THREAD

**Issue by Devnol** [voidcosmos/npkill#91] opened 2021-03-30 19:09 UTC
**Describe the bug**
Running npkill in macOS from the home directory provides the home directory itself as an option to delete which is potentially dangerous

**To Reproduce**
1. `cd` to `~/` (`/Users/username`)
2. run `npx npkill` (use `-s size` to make it show up top)
3. Wait a bit for the scan to progress
4. See the releasable space be insanely massive and be given `/Users/username` (as well as `/Users/username/Library`) as an option

**Expected behavior**
These two do not show up as they do not include just node_modules but also all user's files. 

**Screenshots**
<img width="1552" alt="Screenshot 2021-03-30 at 22 06 59" src="https://user-images.githubusercontent.com/58105634/113042776-40a2b080-91a4-11eb-91cd-b99d09096ef9.png">

 - OS: macOS 11.2.3
 - Version: v0.7.4

**Additional context**
npkill invoked with `npx npkill -s size`, running using node installed by nvm

**Comment by zaldih** [comment] 2021-04-03 14:07
Duplicate of #40

**Closed by zaldih** 2021-04-03 14:07 UTC
Labels: duplicate
