### ISSUE TITLE
[BUG] Wrong scan results

### ISSUE THREAD

**Issue by roojay520** [voidcosmos/npkill#78] opened 2020-06-12 02:19 UTC
**Describe the bug**
My MAC only has 500 GB of hard disk 😅
![image](https://user-images.githubusercontent.com/11495164/84457833-386d9900-ac96-11ea-9f7d-6719bb25859d.png)

 - OS: macOS 10.14.6 
 - Version: v0.7.1

**Comment by LosYear** [comment] 2020-06-13 12:24
I have the same issue

**Comment by danielpox** [comment] 2021-02-25 20:01
Same here. 500 GB SSD but it says I have 990 GB of releasable space!

**Comment by danielpox** [comment] 2021-02-26 20:43
I found a way to circumvent this! The problem, as also depicted in the screenshot above, is that it for some reason includes the current directory as a whole, and even all parent directories up to the user directory.

To prevent this you can try adding these parameters: `-d .` (in context `npx npkill -d .`), which explicitly tells npkill to look in *this very directory and downwards*. It worked for me, and didn't include *my entire user directory!*

**Comment by zaldih** [comment] 2021-04-03 15:42
Hey @danielpox  good discovery!!! 
It seems that all the problems some users have related to the spacing issue is caused by that (but you couldn't tell unless you used the --sort size parameter to make it clearly visible).


This same issue is open here #40 , so I'll close this one to focus the discussion there.

**Closed** 2021-04-16 13:45 UTC
Labels: duplicate
