### ISSUE TITLE
TypeError: this.stdin.setRawMode is not a function

### ISSUE THREAD

**Issue by briandesousa** [voidcosmos/npkill#15] opened 2019-08-15 19:29 UTC
First of all.. this is a fantastic idea for a tool, thank you!

**Describe the bug**
Installed npkill on my Windows 10 machine and tried running it for the first time but I get this error:
```
TypeError: this.stdin.setRawMode is not a function
    at Controller.setRawMode (C:\nvm\v12.7.0\node_modules\npkill\lib\controller.js:142:20)
    at Controller.prepareScreen (C:\nvm\v12.7.0\node_modules\npkill\lib\controller.js:116:14)
    at new Controller (C:\nvm\v12.7.0\node_modules\npkill\lib\controller.js:40:14)
    at Object.<anonymous> (C:\nvm\v12.7.0\node_modules\npkill\lib\index.js:18:22)
    at Module._compile (internal/modules/cjs/loader.js:777:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:788:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:840:10)
    at internal/main/run_main_module.js:17:11
```
**To Reproduce**
1. Install npkill@0.3.0 on Windows 10 
2. Run npkill
3. See error

**Expected behavior**
npkill CLI interface

**Screenshots**
![image](https://user-images.githubusercontent.com/5022414/63120813-12da0b00-bf71-11e9-8104-de637e469029.png)

 - OS: Windows 10 Professional 1903, build 18956.1000 (insiders fast ring)
 - npkill version: v0.3.0
 - NodeJS version: 12.7.0

**Additional context**

**Comment by zaldih** [comment] 2019-08-15 19:50
Hi Briandesousa.

Thank you for opening this issue and for your comment!

I've been looking for the cause of the error and... it seems to be git bash !

Could you try to launch the command from the cmd?

**Comment by briandesousa** [comment] 2019-08-15 19:52
Good idea. Tried and it works as expected on the normal windows command line. If I have some extra time, I'll poke around and see if I can figure out why bash fails. Thanks again!

**Comment by zaldih** [comment] 2019-08-15 20:11
Awesome!
I also have no idea why it fails, but I smell that it may be something related to TTY.

Of course you have discovered an important bug since there are many who use git bash in windows (I included, until I started using cmder).

**The solution for now is to use another console interpreter like CMD.**

**Comment by zaldih** [comment] 2019-08-21 14:30
I have added a function to notify when the terminal is not compatible
https://github.com/voidcosmos/npkill/commit/63ebc48c5a247280934c57507a1a6ca0c3b04e07

**Comment by zaldih** [comment] 2019-08-23 19:17
I will close the issue.
Do not hesitate to open it again if you get any news!
Thanks !

**Closed** 2019-08-23 19:18 UTC
Labels: solution inside

**Comment by amal-san** [comment] 2023-05-18 07:32
same error was shown on debug console in vscode while running source code. Changing `"console": "integratedTerminal"` in launch.json made default shell as bash.
